openapi: 3.0.3
info:
  title: Authentication API
  description: API for user authentication and profile management
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /auth/me:
    get:
      summary: Get authenticated user profile
      description: Retrieve the profile of the currently authenticated user including onboarding data
      operationId: getAuthenticatedUser
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              examples:
                user_profile:
                  summary: Example user profile
                  value:
                    id: "user-123"
                    email: "user@example.com"
                    experience_level: "intermediate"
                    background: "software"
                    background_detail: "Software engineer with 5 years experience"
                    created_at: "2025-12-19T10:00:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from Better Auth service

  schemas:
    UserProfile:
      type: object
      required:
        - id
        - email
        - experience_level
        - background
      properties:
        id:
          type: string
          description: Unique user identifier
          example: "user-123"
        email:
          type: string
          format: email
          description: User's email address
          example: "user@example.com"
        experience_level:
          type: string
          enum: [beginner, intermediate, advanced]
          description: User's experience level
          example: "intermediate"
        background:
          type: string
          enum: [software, hardware, other]
          description: User's background
          example: "software"
        background_detail:
          type: string
          nullable: true
          description: Additional details about user's background
          example: "Software engineer with 5 years experience"
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
          example: "2025-12-19T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2025-12-19T10:00:00Z"

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Unauthorized"
        message:
          type: string
          description: Detailed error message
          example: "Authentication token is missing or invalid"

  responses:
    UnauthorizedError:
      description: Authentication token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ForbiddenError:
      description: User does not have permission to access this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'